views/bike_details.py
from flask import Blueprint, render_template, redirect, url_for

from services.bike_service import BikeService

bike_details = Blueprint('bike_details', __name__)

@bike_details.route('/<bike_id>')
def page(bike_id: int):
    bike = BikeService.get_bike_by_id(bike_id)
    if not bike:
        return redirect(url_for("index.page"))
    return render_template("bike_details/page.jinja",bike=bike,available=BikeService.is_bike_available(bike_id))

views/borrow.py
from datetime import datetime

from flask import Blueprint, render_template, request, flash, redirect, url_for, session

from auth import login_required
from services.bike_service import BikeService
from services.borrow_service import BorrowService

borrow = Blueprint('borrow', __name__)

@borrow.route('/<bike_id>', methods=['GET', 'POST'])
@login_required
def page(bike_id):
    available = BikeService.is_bike_available(bike_id)
    if not available:
        return redirect(url_for('index.page'))
    if request.method == 'POST':
        flash("Borrow was successful. Please visit our store to claim your bike.", category='success')
        BorrowService.borrow(bike_id,session['id'],datetime.fromisoformat(request.form['to']).strftime('%Y-%m-%d %H:%M:%S'),request.form['payment_method'])
        return redirect(url_for('index.page'))
    else:
        bike = BikeService.get_bike_by_id(bike_id)
        return render_template("borrow/page.jinja", bike=bike)

templates/index/bikes.jinja
<div class="bikes-grid gap-4 w-full">
    {% for bike in bikes %}
        <div
                onclick="window.location.href= '{{ url_for("bike_details.page", bike_id=bike.bike_id) }}'"
                class="cursor-pointer w-full border border-titan-500 rounded p-2 flex flex-col justify-between"
        >
            <div>
                <img src="data:image/jpeg;base64,{{ bike.image }}" alt="">
                <h3 class="text-center text-xl font-bold">{{ bike.name }}</h3>
                <p class="text-titan-400 text-sm">{{ bike.description }}</p>
            </div>
            <div>
                <div class="text-right mt-4 text-2xl font-bold">{{ bike.price }} CZK/day</div>
                <div class="mt-4 flex justify-end">
                    {% if bike.is_available %}
                        <a href="{{ url_for("borrow.page", bike_id=bike.bike_id) }}"
                           class="p-1 px-4 bg-primary-500 text-titan-50 rounded no-underline">Borrow
                        </a>
                    {% else %}
                        Not available
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
</div>

templates/index/filter.jinja
<aside class="border border-titan-600 rounded-md h-fit md:max-w-72" oninput="updateForm()">
    <div class="p-4 flex items-center justify-between" onclick="toggleFilter()">
        <h1 class="text-lg font-bold">Filter</h1>
        <div class="md:hidden">
            <img id="filter-chevron" width="24" src="{{ url_for('static', filename="img/chevron-left.svg") }}">
        </div>
    </div>

    <div id="filter-content" class="p-4 pt-0 hidden md:block">
        <hr>
        <h2 class="font-bold">Availability</h2>
        <div class="filter">
            <span>
                <input type="checkbox" name="available" value="true" {% if form.get("available") == 'true' or form|length == 0 %}checked{% endif %}>
                <label>Available</label>
            </span>
            <span>
                <input type="checkbox" name="not-available" value="true" {% if form.get("not-available") == 'true' or form|length == 0 %}checked{% endif %}>
                <label>Not Available</label>
            </span>
        </div>
        <hr>
        <h2 class="font-bold">Weight</h2>
        <div class="filter">
            <span>
                {{ filters[0][0]  }}
            </span>
            <input
                    type="range"
                    name="weight"
                    min="{{ filters[0][0] }}"
                    max="{{ filters[0][1] }}"
                    value="{{ form["weight"] or filters[0][1] }}"
            >
            <span>
                {{ filters[0][1]  }}
            </span>
        </div>
        <div id="filter-weight" class="text-center">{{ form["weight"] or filters[0][1] }}</div>
        <hr>
        <h2 class="font-bold">Weight limit</h2>
        <div class="filter">
            <span>{{ filters[1][0]  }}</span>
            <input type="range" name="weight_lim" min="{{ filters[1][0] }}"
                                   max="{{ filters[1][1] }}" value="{{ form["weight_lim"] or filters[1][1] }}">
            <span>{{ filters[1][1]  }}</span>
        </div>
        <div id="filter-weight-lim" class="text-center">{{ form["weight_lim"] or filters[1][1] }}</div>
        <hr>
        <h2 class="font-bold">Body size</h2>
        <div class="filter">
            {% for size in filters[2] %}
                <span><input name="size" type="checkbox" value="{{ size[0] }}" {% if size[0] in form.getlist('size')%}
                             checked{% endif %}><label>{{ size[0] }}
                    </label>
                </span>
            {% endfor %}
        </div>
        <hr>
        <h2 class="font-bold">Wheel size</h2>
        <div class="filter">
            {% for wsize in filters[3] %}
                <span><input name="wsize" type="checkbox" value="{{ wsize[0] }}" {% if wsize[0] in
                        form.getlist('wsize')%}checked{% endif %}><label>{{ wsize[0] }}
                    </label>
                </span>
            {% endfor %}
        </div>
        <hr>
        <h2 class="font-bold">Material</h2>
        <div class="filter">
            {% for material in filters[4] %}
                <span><input name="material" type="checkbox" value="{{ material[0] }}" {% if material[0] in
                        form.getlist('material')%}checked{% endif %}>
                    <label class="filter-label">{{ material[0] }}</label></span>
            {% endfor %}
        </div>
        <hr>
        <h2 class="font-bold">Gear</h2>
        <div class="filter">
            {% for gear in filters[5] %}
                <span>
                    <input name="gear" type="checkbox" value="{{ gear[0] }}"
                        {% if gear[0]|string in form.getlist('gear')%}checked{% endif %}>
                    <label>{{ gear[0] }}</label>
                </span>
            {% endfor %}
        </div>
        <hr>
        <h2 class="font-bold">Price</h2>
        <div class="filter">
            <span>{{ filters[6][0] }}</span>
            <input type="range" name="bprice" min="{{ filters[6][0] }}" max="{{ filters[6][1] }}" value="{{ form["bprice"] or filters[6][1] }}">
            <span>{{ filters[6][1] }}</span>
        </div>
        <hr>
        <div id="filter-bprice" class="text-center">{{ form["bprice"] or filters[6][1] }}</div>

        <span class="flex justify-end"><button class="bg-primary px-2 py-2 my-1 rounded-md text-titan-50
                                                        text-sm" type="submit">Apply</button>
        </span>
    </div>
    <script>
        const toggleFilter = () => {
            console.log("z")
            const content = document.getElementById("filter-content")
            content.classList.toggle("hidden")
            document.getElementById("filter-chevron").src = content.classList.contains("hidden")
                ? "{{ url_for('static', filename="img/chevron-left.svg") }}"
                : "{{ url_for('static', filename="img/chevron-down.svg") }}"
        }
        const updateForm = () => {
            const form = document.querySelector("form")
            document.getElementById("filter-weight").innerText = form.weight.value
            document.getElementById("filter-weight-lim").innerText = form.weight_lim.value
            document.getElementById("filter-bprice").innerText = form.bprice.value
        }
        updateForm()
    </script>
</aside>

templates/index/page.jinja
{% extends '__page.jinja' %}

{% block title %}Homepage{% endblock %}

{% block body %}
	<h1 class="text-3xl mb-4 font-bold">Our sortiment</h1>
    <form method="get">
        <div class="border border-titan-600 rounded-md p-1">
                <input type="search" action="/" name="search"
                   class="bg-no-repeat bg-left pl-7 focus:outline-none
                   w-full" placeholder="Search for a bike..."
                   {% if request.args.get('search') %}
                        value="{{ request.args.get("search") }}"
                   {% endif %}
                    style="background-image: url('{{ url_for('static', filename="img/search.svg") }}');background-size: 1.5rem 1rem"
                   onblur="search()">
        </div>
        <div class="flex gap-8 mt-8 flex-col md:flex-row">
            {% include 'index/filter.jinja' %}
            {% include 'index/bikes.jinja' %}
        </div>
    </form>
    <script>
        function search(){
            document.getElementsByName("search").submit()
        }
    </script>
{% endblock %}