views/index.py
from flask import Blueprint, render_template, request, redirect

from services.bike_service import BikeService

index = Blueprint('index', __name__)

@index.route('/', methods=['GET','POST'])
def page():
    if len(request.args) > 0:
        show = BikeService.get_all_to_show_by_filter(
            bool(request.args.get("available")),
            bool(request.args.get("not-available")),
            request.args.get("weight"),
            request.args.get("weight_lim"),
            request.args.getlist("size"),
            request.args.getlist("wsize"),
            request.args.getlist("material"),
            request.args.getlist("gear"),
            request.args.get('search'),
            request.args.get("bprice")
        )
    else:
        show = BikeService.get_all_to_show()
    filters = BikeService.get_filters()
    return render_template(
        'index/page.jinja', bikes=show, filters=filters, form=request.args)

views/register_page.py
from flask import Blueprint, request, redirect, url_for, flash, render_template

from auth import guest_required
from form import RegisterForm
from services.user_service import UserService

register_page = Blueprint('register_page', __name__)

@register_page.route('/', methods=["GET", "POST"])
@guest_required
def page():
    form = RegisterForm()
    if request.method == "POST" and form.validate_on_submit():
        if form.password.data == form.password_again.data:
            input_data = form.data
            input_data.pop("password_again")
            input_data.pop("csrf_token")
            UserService.register(**input_data)
            flash("Successfully registered! Now please login!",category="success")
            return redirect(url_for("login_page.page"))
        flash("Passwords do not match",category="error")
    return render_template("register_page/page.jinja", form=form)

templates/register_page/page.jinja
{% extends '__page.jinja' %}
{% from 'macros/form.jinja' import form_field, form_submit, form_cancel %}

{% block title %}
    Register
{% endblock %}
{% block body %}
    <div class="h-full grow flex items-center justify-center">
        <div class="flex flex-col items-center bg-titan-100 p-2 gap-1 w-60 rounded-md border border-titan-500">
            <h1 class="text-xl font-bold mb-1">Register</h1>
            <form method="post">
                {{ form.hidden_tag() }}
                {{ form_field(form.login) }}
                {{ form_field(form.first_name) }}
                {{ form_field(form.last_name) }}
                {{ form_field(form.email) }}
                {{ form_field(form.phone_number) }}
                <hr class="border-titan-500 my-5">
                {{ form_field(form.password) }}
                {{ form_field(form.password_again) }}
                <div class="flex justify-end gap-20">
                    <div class="mt-4 mb-1">{{ form_cancel(redirect=url_for('index.page')) }}</div>
                    <div class="mt-4 mb-1">{{ form_submit("Register") }}</div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}